Fail code-style step if apply makes changes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -49,8 +49,15 @@ jobs:
         if: always()
         run: ./gradlew spotlessApply
 
+      - name: Fail step if changes exist
+        run: |
+          if [[ $(git diff --stat .) != '' ]]; then
+            # If there are changes, fail this step
+            exit 1
+          fi
+
       - name: Push changes to PR if exist
-        if: ${{ github.event_name == 'pull_request' }}
+        if: always() && ${{ github.event_name == 'pull_request' }}
         run: |
           # If there are any changes from running spotlessApply, push to PR
           if [[ $(git diff --stat .) != '' ]]; then
